<?php
/**
 * @file
 * Code for the Leidos feature.
 */

include_once 'leidos.features.inc';

/**
 * Implements hook_form_alter().
 */
function leidos_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#entity_type']) && $form['#entity_type'] == 'fieldable_panels_pane') {
    // Hide some unnecessary fields that clutter the IPE user interface.
    $form['link']['#access'] = FALSE;
    $form['view_mode']['#access'] = FALSE;
  }
  elseif ($form_id == 'panels_panel_context_edit_choose') {
    // Set the default panel layout to Industry Template, remove other layouts.
    $form['categories']['#default_value'] = 'Industry-Template';
    $form['layout']['Industry-Template']['flexible:industry_template']['#default_value'] = 'flexible:industry_template';
    unset($form['categories']['#options']['Builders']);
    unset($form['categories']['#options']['Columns-1']);
    unset($form['categories']['#options']['Columns-2']);
    unset($form['categories']['#options']['Columns-3']);
  }
}
