<?php
/**
 * @file
 * Code for the Flexible Template feature.
 */

include_once 'flexible_template.features.inc';

/**
 * Implements template_preprocess_entity().
 */
function flexible_template_preprocess_entity(&$variables, $hook) {
  $function = 'flexible_template_preprocess_' . $variables['elements']['#bundle'];
  if (function_exists($function)) {
    $function($variables, $hook);
  }
}

/**
 * Implements template_preprocess_panels_pane().
 */
function flexible_template_preprocess_panels_pane(&$variables) {
  $content = &$variables['content'];

  // Set background color.
  if (isset($content['field_background_color'])) {
    $variables['attributes_array']['style'][] = 'color:' . $content['field_background_color']['#items'][0]['rgb'];
    unset($variables['content']['field_background_color']);
  }

  // Set title color.
  if (!empty($content['field_title_color']['#items'][0]['rgb'])) {
    $variables['title_attributes_array']['style'][] = 'color:' . $content['field_title_color']['#items'][0]['rgb'];
    unset($variables['content']['field_title_color']);
  }

  // Set title size.
  if (!empty($content['field_title_size'][0]['#markup'])) {
    $variables['title_heading'] = $content['field_title_size'][0]['#markup'];
    unset($variables['content']['field_title_size']);
  }

  flexible_template_preprocess_subhead($variables);
}

/**
 * Field collection implementation of template_preprocess_entity().
 *
 * The $variables array contains the following arguments:
 * - $node
 * - $view_mode
 * - $page
 */
function flexible_template_preprocess_field_collection_item(&$variables) {
  $content = &$variables['content'];

  // Set title color.
  if (isset($content['field_title_color'])) {
    $variables['content']['field_title_item'][0]['#attributes'] = array('style' => 'color:' . $content['field_title_color']['#items'][0]['rgb']);
    unset($variables['content']['field_title_color']);
  }

  // Set title size.
  if (isset($content['field_title_size'])) {
    if (isset($content['field_title_item'])) {
      $variables['content']['field_title_item'][0]['#theme'] = 'html_tag';
      $variables['content']['field_title_item'][0]['#tag']   = $content['field_title_size'][0]['#markup'];
      $variables['content']['field_title_item'][0]['#value'] = $content['field_title_item'][0]['#markup'];
    }
    unset($variables['content']['field_title_size']);
  }

  flexible_template_preprocess_subhead($variables);
}

function flexible_template_preprocess_field_columns_multi(&$variables) {
  flexible_template_preprocess_field_collection_item($variables);
}

function flexible_template_preprocess_field_icon_item(&$variables) {
  flexible_template_preprocess_field_collection_item($variables);
}

function flexible_template_preprocess_field_thumbnail_image_item(&$variables) {
  flexible_template_preprocess_field_collection_item($variables);
}

/**
 * Preprocess Subtitle field value.
 *
 * The $variables array contains the following arguments:
 * - $node
 * - $view_mode
 * - $page
 */
function flexible_template_preprocess_subhead(&$variables) {
  $content = $variables['content'];

  // Set subhead color.
  if (isset($content['field_subhead_color'])) {
    $variables['content']['field_subhead'][0]['#attributes'] = array('style' => 'color:' . $content['field_subhead_color']['#items'][0]['rgb']);
    unset($variables['content']['field_subhead_color']);
  }

  // Set subhead size.
  if (isset($content['field_subhead_size'])) {
    $variables['content']['field_subhead'][0]['#theme'] = 'html_tag';
    $variables['content']['field_subhead'][0]['#tag']   = $content['field_subhead_size'][0]['#markup'];
    $variables['content']['field_subhead'][0]['#value'] = $content['field_subhead'][0]['#markup'];
    unset($variables['content']['field_subhead_size']);
  }
}
