<?php
/**
 * @file
 * Code for the Announcements feature.
 */

include_once 'announcements.features.inc';

/**
 * Implements hook_block_info().
 */
function announcements_block_info() {
  // Announcements media block.
  $blocks['announcements_media'] = array(
    'info'  => t('Announcment Media'),
  );
  return $blocks;
}

/*
* Implements hook_block_view().
*/
function announcements_block_view($delta = '') {
  switch ($delta) {
    case 'announcements_media':
      $node = menu_get_object();

      // Alignment.
      $alignment = '';
      if (isset($node->field_media_placement[LANGUAGE_NONE])) {
        $alignment = $node->field_media_placement[LANGUAGE_NONE][0]['value'];
      }
      // Image.
      $image = '';
      if (isset($node->field_image[LANGUAGE_NONE])) {
        $uri = $node->field_image[LANGUAGE_NONE][0]['uri'];
        $image = image_style_url('announcement_detail', $uri);
      }
      // Video.
      $video = '';
      if (isset($node->field_video_tout[LANGUAGE_NONE])) {
        $uri = $node->field_video_tout[LANGUAGE_NONE][0]['uri'];
        $mime = $node->field_video_tout[LANGUAGE_NONE][0]['filemime'];
        $video = file_create_url($uri);
        if ($mime == 'video/youtube') {
          // YouTube video.
          $video = str_replace('watch?v=', 'embed/', $video);
          $video = '<iframe width="660" height="320" src="' . $video . '" frameborder="0" allowfullscreen></iframe>';
        }
        else {
          // Uploaded video.
          $video = '
          <video controls="controls">
            <source src="' . $video .'" type="' . $mime . '">
          </video>';
        }
      }
      // Caption.
      $caption = '';
      if (isset($node->field_image_caption[LANGUAGE_NONE])) {
        $caption = $node->field_image_caption[LANGUAGE_NONE][0]['value'];
      }
      // Icons links.
      $icons = '';
      if (isset($node->field_icon_item[LANGUAGE_NONE])) {
        foreach ($node->field_icon_item[LANGUAGE_NONE] as $key => $icon_item) {
          $icon = field_collection_item_load($icon_item['value']);
          $uri = $icon->field_image[LANGUAGE_NONE][0]['uri'];
          $icon_image = image_style_url('announcement_icon', $uri);
          $title = $icon->field_image_link[LANGUAGE_NONE][0]['title'];
          $url = $icon->field_image_link[LANGUAGE_NONE][0]['url'];
          $output = '
          <div class="icon">
            <image src="' . $icon_image . '">
            <span class="title">'. $title . '</span>
          </div>';
          $icons .= l($output, $url, array('html' => TRUE));
        }
      }
      // Body.
      $body = '';
      if (isset($node->body[LANGUAGE_NONE])) {
        $body = $node->body[LANGUAGE_NONE][0]['value'];
      }
      // Render the themed media section.
      $block['content'] = theme(
        'announcements_media',
        array(
          'alignment' => $alignment,
          'image' => $image,
          'video' => $video,
          'caption' => $caption,
          'icons' => $icons,
          'body' => $body,
        )
      );
      break;
  }
  return $block;
}

/*
* Implements hook_theme().
*/
function announcements_theme() {
  return array(
    'announcements_media' => array(
      'variables' => array(
        'alignment' => '',
        'image' => '',
        'video' => '',
        'caption' => '',
        'icons' => '',
        'body' => ''
      ),
      'template' => 'templates/announcements-media',
    ),
  );
}
