<?php include("opening.html"); ?>


<div class="staticContent careersLanding">

    <section class="marqueeImage marqueeImage--simple">
        <div class="marqueeImage__image"></div>
        <div class="marqueeImage__overlay"></div>
    </section>

    <div class="careersHero">
        <div class="careersHero__left">
            <section class="forwardThinkers">
                <header>
                    <h2>Now Seeking Forward Thinkers</h2>
                    <span>Join Leidos to help make our communities, our nation, and our world a better place for generations to come.</span>
                </header>

                <div class="careersSearch">
                    <form name="careers-keyword-search" id="keywordSearch" method="get" enctype="multipart/form-data" action="http://jobs.leidos.com/search/">
                        <div class="inputWithButton">
                            <input id="keywords" name="q" type="text" class="text" placeholder="Keywords, Job ID, or Title" />
                            <button type="submit" class="searchSubmit">Submit<span></span></button>
                        </div>
                    </form>
                </div>
                <p>Already submitted a resume? <a href="">Access your existing profile&nbsp;»</a></p>

                <p>Are you a Leidos employee? <a href="">Access your employee profile here&nbsp;»</a></p>

                <p><strong>Having Technical Issues Applying to a Position?</strong> If you are having technical issues applying to a position on leidos.com/careers, we’d be happy to assist. <a href="">Request help now&nbsp;»</a></p>

                <p><strong>Accommodation Request</strong> - If you have a disability and need help using leidos.com/careers, we'd be happy to lend a hand. <a href="">Request help now&nbsp;»</a></p>

                <p>Leidos will never ask you to provide payment-related information at any part of the employment application process. We will only communicate with you through emails that are generated by our automated system. If you receive an email claiming to be from Leidos that asks for payment-related information or any other personal information, please report the email to Chris Scalia, VP of Talent Acquisition, at <a href="">chris.a.scalia@leidos.com</a>.</p>
            </section>
        </div>

        <div class="careersHero__right">
            <section class="findYourChallenge">
                <header>
                    <h2>FIND YOUR <span>NEXT CHALLENGE</span></h2>
                </header>
                <p>Learn more about career opportunities at Leidos at every level of experience and across our core business areas.</p>
                <a href="/careers/opportunities/" class="cta cta__primary">See Opportunities<span class="arrowRight"></span></a>
            </section>

            <section class="searchForJobs">
                <header>
                    <h2>Search Jobs</h2>
                    <ul>
                        <li><a href="http://jobs.leidos.com#life-at-leidos"><span>Featured Opportunities</span></a></li>
                        <li><a href="https://www.linkedin.com/vsearch/j?page_num=1&locationType=Y&f_C=2927821%2C3615259%2C2973906&trk=jobs_biz_prem_all"><span>Recently Posted</span></a></li>
                        <li><a href="http://jobs.leidos.com/List/Cities"><span>By Location</span></a></li>
                    </ul>
                </header>
                <img src="https://www.leidos.com/sites/default/files/hp-map-img.png" width="340" height="178" alt="World map">
                <p>Leidos is an Equal Opportunity Employer - <a href="/EEO">EEO is the Law Poster and Supplements</a>.</p>
            </section>
        </div>
    </div>

    <nav class="fixedNav">
        <ul>
            <li>
                <a href="#life-at-leidos">Life at Leidos</a>
            </li>
            <li>
                <a href="#getting-ready">Our Values</a>
            </li>
            <li>
                <a href="#faqs">Careers FAQs</a>
            </li>
            <li>
                <a href="#pay-benefits">Pay &amp; Benefits</a>
            </li>
            <li>
                <a href="/careers/e-verify" class="noPad"><img width="124" height="30" src="https://www.leidos.com/sites/default/files/E-Verify_Logo_4-Color_CMYK_Vector_SM_EPS.png""></a>
            </li>
            <li>
                <span>
                    <a href="https://twitter.com/leidosjobs" class="twitter-follow-button" data-show-count="false">Follow @leidosjobs</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </span>
                <span>
                    <script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
                    <script type="IN/FollowCompany" data-id="162356" data-counter="none"></script>
                </span>
            </li>
        </ul>
    </nav>

    <section class="imageTout imageTout--imgFull imageTout--doubleText" id="life-at-leidos">
        <heading class="subhead">
            <h2 class="subhead__head subhead__head--withLink">Life at Leidos</h2>
            <a href="/careers/life/" class="subhead__link">View All&nbsp;»</a>
        </heading>
        <img class="imageTout__image" src="https://www.leidos.com/sites/default/files/lifeAtLeidos.jpg" width="1000" height="320" alt="">
        <div class="imageTout__meta">
            <heading>
                <h2>Balance Work & Life</h2>
            </heading>
            <p>
                At Leidos, we offer meaningful and engaging careers, a collaborative culture, and support for your career goals, all while nurturing a healthy work-life balance.
            </p>
            <a href="/careers/life#tab/our-culture"><span>Learn More&nbsp;»</span></a>
        </div>
        <div class="imageTout__meta">
            <heading>
                <h2>Build Your Career</h2>
            </heading>
            <p>
                Grow with us. We offer resources for professional development and learning, complemented by flexible career paths and an inclusive environment.
            </p>
            <a href="/careers/life#tab/build-your-career"><span>Learn More&nbsp;»</span></a>
        </div>
    </section>

    <section class="imageToutCarousel" id="getting-ready">
        <heading class="subhead">
            <h2 class="subhead__head subhead__head--withLink">Our Values</h2>
            <a href="/careers/life#tab/our-values" class="subhead__link">View All&nbsp;»</a>
        </heading>
        <div class="imageToutCarousel__items">
            <div class="imageToutCarousel__item">
                <img class="imageToutCarousel__image" src="https://www.leidos.com/sites/default/files/01.jpg" width="280" height="280" alt="">
                <div class="imageToutCarousel__counter">1</div>
                <div class="imageToutCarousel__meta">
                    <h3><span class="imageToutCarousel__mobileCounter">1</span> INSPIRED to make a difference</h3>
                    <p>We are committed to solving the world’s toughest problems. We achieve this by connecting our employees’ knowledge and our superior technologies across Leidos in pursuit of answers. We know that by embracing the differences of all employees we will unlock the creativity and innovation that makes a difference.</p>
                </div>
            </div>
            <div class="imageToutCarousel__item">
                <img class="imageToutCarousel__image" src="https://www.leidos.com/sites/default/files/02.jpg" width="280" height="280" alt="">
                <div class="imageToutCarousel__counter">2</div>
                <div class="imageToutCarousel__meta">
                    <h3><span class="imageToutCarousel__mobileCounter">2</span> PASSIONATE about customer success</h3>
                    <p>We are determined to understand and respond to our customers’ needs as if they were our own. This plus our dedication to deliver superior results ensures that we will create solutions that lead our markets.</p>
                </div>
            </div>
            <div class="imageToutCarousel__item">
                <img class="imageToutCarousel__image" src="https://www.leidos.com/sites/default/files/03.jpg" width="280" height="280" alt="">
                <div class="imageToutCarousel__counter">3</div>
                <div class="imageToutCarousel__meta">
                    <h3><span class="imageToutCarousel__mobileCounter">3</span> UNITED as a team</h3>
                    <p>We are bound together by our conviction that ethics and integrity are core to how we operate. We engage with others from a basis of trust because we believe that everyone is doing his or her best and wants to do the right thing. Therefore, we collaborate and share to create value for our employees, our shareholders and our communities.</p>
                </div>
            </div>
            <div class="imageToutCarousel__item">
                <img class="imageToutCarousel__image" src="https://www.leidos.com/sites/default/files/04.jpg" width="280" height="280" alt="">
                <div class="imageToutCarousel__counter">4</div>
                <div class="imageToutCarousel__meta">
                    <h3><span class="imageToutCarousel__mobileCounter">4</span> INTEGRITY is the foundation for all that we do</h3>
                    <p>At Leidos we have a steadfast commitment to integrity and ethical behavior in all that we do. This includes interactions with employees, customers and our communities.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="imageTout imageTout--imgFull imageTout--tripleText" id="pay-benefits">
        <heading class="subhead">
            <h2 class="subhead__head subhead__head--withLink">Pay & Benefits</h2>
            <a href="/careers/pay-benefits/" class="subhead__link">View All&nbsp;»</a>
        </heading>
        <img class="imageTout__image" src="https://www.leidos.com/sites/default/files/payAndBenefits.jpg" width="1000" height="320" alt="">
        <div class="imageTout__meta">
            <heading>
                <h2>Compensation</h2>
            </heading>
            <p>
                We reward your contributions to the company and our customers' mission, recognizing notable advances in your field.
            </p>
            <a href="/careers/pay-benefits/"><span>Learn More&nbsp;»</span></a>
        </div>
        <div class="imageTout__meta">
            <heading>
                <h2>Health Coverage</h2>
            </heading>
            <p>
                Benefits start immediately, with no waiting period, no exclusions for pre-existing conditions, and comprehensive coverage for employees and their eligible dependents.
            </p>
            <a href="/careers/pay-benefits/"><span>Learn More&nbsp;»</span></a>
        </div>
        <div class="imageTout__meta">
            <heading>
                <h2>Wellness</h2>
            </heading>
            <p>
                Certain locations provide full-service fitness centers which offer cardio and strength training equipment, as well as group exercise classes.
            </p>
            <a href="/careers/pay-benefits/"><span>Learn More&nbsp;»</span></a>
        </div>
    </section>

    <section class="fullWidthText fullWidthText--fourBlocks" id="faqs">
        <heading class="subhead">
            <h2 class="subhead__head subhead__head--withLink">Careers FAQs</h2>
            <a href="/careers/faqs/" class="subhead__link">View All&nbsp;»</a>
        </heading>
        <ul>
            <li>
                <h3>What is the status of my application?</h3>
                <p><a href="https://leidos.taleo.net/careersection/iam/accessmanagement/login.jsf?lang=en&redirectionURI=https%3A%2F%2Fleidos.taleo.net%2Fcareersection%2Fprofile.jss%3Flang%3Den%26type%3D1%26csNo%3D10000%26portal%3D2140483457%26postdata%3D%24_fgZgAy-cm_-Uy1pk22i6A%3D%3D&TARGET=https%3A%2F%2Fleidos.taleo.net%2Fcareersection%2Fprofile.jss%3Flang%3Den%26type%3D1%26csNo%3D10000%26portal%3D2140483457%26postdata%3D%24_fgZgAy-cm_-Uy1pk22i6A%3D%3D">Log into your Candidate Profile</a> and go to the "My Job" page. You'll be able to see your application's current status and whether the position you applied for is still open.</p>
            </li>
            <li>
                <h3>Where can I find benefits information?</h3>
                <p>You'll find general information about our compensation packages in the <a href="/careers/pay-benefits/">Pay & Benefits</a> section. You'll get more specifics when extended a job offer.</p>
            </li>
            <li>
                <h3>How do I send an updated resume?</h3>
                <p>To update a job submission, go to the "My Job" page, find the submission you want to update, click "View/Edit Submission", make your edits, and submit changes.</p>
            </li>
            <li>
                <h3>How will I know if you've received my resume?</h3>
                <p>You'll get an automatic email confirmation as soon as you register and submit your resume via this site.</p>
            </li>
        </ul>
    </section>

</div>

<script type="text/javascript" src="/sites/all/themes/leidos/static-pages/js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/sites/all/themes/leidos/static-pages/js/jquery.jscrollpane.min.js"></script>
<script type="text/javascript" src="/sites/all/themes/leidos/static-pages/js/jquery.sticky.js"></script>
<script type="text/javascript" src="/sites/all/themes/leidos/static-pages/js/slick.min.js"></script>


<?php include("closing.html"); ?>
